version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./service_minio/data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 admin password;
      mc mb myminio/mlflow-artifacts --ignore-existing;
      exit 0;
      "
    networks:
      - my_network

  mlflow:
    image: python:3.9-slim
    container_name: mlflow
    ports:
      - "5000:5000"
    working_dir: /mlflow
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
    command: >
      sh -c "
      pip install mlflow boto3 &&
      mlflow ui --host 0.0.0.0 --port 5000 --default-artifact-root s3://mlflow-artifacts/ --serve-artifacts
      "
    depends_on:
      createbuckets:
        condition: service_completed_successfully
    networks:
      - my_network

networks:
  my_network:
    external: true 