version: '3'
services:
  app:
    image: ui:latest
    ports:
      - "80:80"
    build:
      dockerfile: deploy/Dockerfile.prod
      context: ..
    volumes:
      - media:/ui/media
      - static:/ui/static
      - ../../ml:/ml
      - uwsgi_logs:/var/log/uwsgi
    environment:
      - DEBUG=False
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    networks:
      - my_network
    restart: always

volumes:
  media:
  static:
  uwsgi_logs:

networks:
  my_network:
    external: true 